autoload :Answer, 'evaluations/answer'
autoload :MetaAnswerItem, 'evaluations/meta_answer_item'
autoload :MetaAnswerOption, 'evaluations/meta_answer_option'
autoload :MetaQuestion, 'evaluations/meta_question'
autoload :MetaSurvey, 'evaluations/meta_survey'
autoload :Question, 'evaluations/question'
autoload :Survey, 'evaluations/survey'